name: venv_ngmt
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.9=h2bbff1b_0
  - pip=23.2.1=py310haa95532_0
  - python=3.10.12=he1021f5_0
  - setuptools=68.0.0=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.41.1
      - kiwisolver==1.4.4
      - matplotlib==3.7.2
      - numpy==1.25.1
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywavelets==1.4.1
      - scipy==1.11.1
      - six==1.16.0
      - tzdata==2023.3
prefix: C:\Users\Project\anaconda3\envs\venv_ngmt
